# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Restro Sync CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build-frontend:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies (frontend)
        working-directory: frontend
        run: npm ci

      - name: Build (frontend)
        working-directory: frontend
        run: npm run build --if-present

  test-frontend:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: build-frontend # Ensure the frontend is built first

    services:
      backend:
        image: het2344/comp4350-g07:backend
        ports:
          - "8018:8018"
        env:
          NODE_ENV: test
          DB_HOST: db
          DB_USER: restro_usr
          DB_PASSWORD: cs4350
          DB_NAME: restro_sync
          DB_PORT: 5432
        options: --health-cmd "curl --fail http://localhost:8018/health || exit 1" --health-interval 5s --health-timeout 5s --health-retries 5

      db:
        image: postgres:latest
        env:
          POSTGRES_USER: restro_usr
          POSTGRES_PASSWORD: cs4350
          POSTGRES_DB: restro_sync
        ports:
          - "5432:5432"
        options: --health-cmd "pg_isready -U restro_usr -d restro_sync" --health-interval 5s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies (frontend)
        working-directory: frontend
        run: npm ci

      - name: Wait for Backend to Be Ready
        run: |
          echo "Waiting for Backend to be ready..."
          until curl --fail http://localhost:8018/health; do
            echo "Backend not ready yet..."
            sleep 5
          done
          echo "Backend is ready!"

      - name: Run Cypress Tests (Headless)
        working-directory: frontend
        run: npm run test:headless

  build-backend:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: npm
          cache-dependency-path: backend/package-lock.json
      - name: Install dependencies (backend)
        working-directory: backend
        run: npm ci
      - name: Build (backend)
        working-directory: backend
        run: npm run build --if-present
      - name: Test (backend)
        working-directory: backend
        run: npm test -- tests/unit

  deploy:
    runs-on: ubuntu-latest
    #needs: [build-frontend, build-backend] # Uncomment if builds should run on push too
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4 # Keep: Needed for files
      - name: Login to Docker Hub
        uses: docker/login-action@v2 # Keep: Needed for push
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      - name: Build and Push with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push
